# Docker image details
image:
  repository: abhijonty/taskmaster
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: NodePort
  port: 31000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: taskmaster.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Replica count
replicaCount: 2

# Resource limits and requests
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

